name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        
        
      - name: Checkout code into go Module directory 
        uses: actions/checkout@v1
        
        
        
     
